conditioning:
  method: mmps
  params:
    scale: 1.0
    maxiter: 1

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    mask_len_range: !!python/tuple [192, 193]  # for box
    mask_prob_range: !!python/tuple [0.99, 0.99]  # for random
    image_size: 256

  noise:
    name: gaussian
    sigma: 0.05
