conditioning:
  method: mmps
  params:
    scale: 1.0
    maxiter: 1

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4

  noise:
    name: gaussian
    sigma: 1.0
